RasaHQ/rasa-sdk

CHANGELOG.rst, Dockerfile, README.md, entrypoint.sh
**Motivation**:
Build a lean standalone Docker image for the rasa core sdk which can be 
* enhanced easily
* connected to a rasa core contaner
* required to implement https://github.com/RasaHQ/rasa_core/issues/845
- adding Dockerfile including an entrypoint file for simpler execution.
=> #19 - added docker image

.travis.yml, rasa_core_sdk/endpoint.py, rasa_core_sdk/forms.py, setup.py
**Suggested Changes**:
- fix pep8 issues
=> fix pep8 issues #21

rasa_core_sdk/events.py, rasa_core_sdk/forms.py
check for `action_no_form_validation` before validating
=> add ability learn when do not validate

rasa_core_sdk/__init__.py
- Included Action's `run()` documentation for sphinx reference
=> Includes run() documentation

rasa_core_sdk/forms.py
pass slots from temp tracker to dispatcher
fixes #27
=> Tracker updated utterance

rasa_core_sdk/events.py
=> added ReminderCancelled event

rasa_core_sdk/events.py, rasa_core_sdk/forms.py, tests/test_forms.py
- finish #44
- together with https://github.com/RasaHQ/rasa_core/pull/1849
=> add from_trigger_intent mapping

CHANGELOG.rst, rasa_core_sdk/version.py
=> Prepare 0.13.0 release

.travis.yml, CHANGELOG.rst, README.md, rasa_core_sdk.toml, rasa_core_sdk/__init__.py, rasa_core_sdk/cli/arguments.py, rasa_core_sdk/endpoint.py, rasa_core_sdk/events.py, rasa_core_sdk/executor.py, rasa_core_sdk/forms.py, rasa_core_sdk/utils.py, rasa_core_sdk/version.py, requirements.txt, setup.cfg, setup.py, tests/test_actions.py, tests/test_endpoint.py, tests/test_forms.py, tests/test_tracker.py
- Reformat code using black
closes #62 
=> Reformat code using black

CHANGELOG.rst, rasa_core_sdk/forms.py, tests/test_forms.py
- fix https://github.com/RasaHQ/rasa_nlu/issues/3194
=> Make validate function validate all extracted slots (even when no slot to fill)

rasa_core_sdk/forms.py, tests/test_forms.py
- Reformat files as build in master failed
=> Reformat files.

rasa_core_sdk/executor.py
- add `utter_custom_json()`
- rename `utter_custom_message()` to `utter_elements()`
- companion to https://github.com/RasaHQ/rasa/pull/3374
=> add utter_custom_json

requirements.txt, setup.py
=> Add check for python version for typing in requirements

CHANGELOG.rst, LICENSE.txt, README.md, rasa_core_sdk/version.py, requirements.txt, setup.py
- increased version number
- changelog update 
- upgraded dependencies
- some cleanup changes in setup.py / License / readme
=> Preparations for release candidate

rasa_core_sdk/executor.py
SDK companion to https://github.com/RasaHQ/rasa/pull/3423
=> persist kwargs to messages

CHANGELOG.rst, rasa_sdk/version.py
seen a couple of people run into issues when they couldnt dispatch images, thought we'd do a release
=> Prepare release 1.1.1

CHANGELOG.rst, rasa_sdk/version.py
- release 1.2.0 to avoid incompatibility warnings
- close https://github.com/RasaHQ/rasa/issues/4167
- close https://github.com/RasaHQ/rasa-sdk/issues/97
=> compatibility release for rasa 1.2.x

CHANGELOG.rst, rasa_sdk/executor.py
- Remove unused `tracker` argument from `utter_template` and `utter_button_template`
=> Remove unused argument

CHANGELOG.rst, rasa_sdk/forms.py
- undid deleted tracker parameter
=> Fix TypeError on request_next_slot method of FormAction class

CHANGELOG.rst, rasa_sdk/__main__.py, rasa_sdk/cli/arguments.py, rasa_sdk/endpoint.py, rasa_sdk/version.py
=> add ssl support

.travis.yml, CHANGELOG.rst, rasa_sdk/__init__.py, rasa_sdk/__main__.py, rasa_sdk/endpoint.py, rasa_sdk/events.py, rasa_sdk/executor.py, rasa_sdk/forms.py, rasa_sdk/interfaces.py, rasa_sdk/utils.py, rasa_sdk/version.py, requirements.txt, setup.py, tests/test_actions.py, tests/test_endpoint.py, tests/test_forms.py, tests/test_tracker.py
=> Python updates

.gitignore, .travis.yml, Makefile, rasa_sdk/endpoint.py, rasa_sdk/events.py, rasa_sdk/executor.py, rasa_sdk/forms.py, rasa_sdk/interfaces.py, rasa_sdk/knowledge_base/actions.py, rasa_sdk/knowledge_base/storage.py, rasa_sdk/knowledge_base/utils.py, rasa_sdk/utils.py, requirements.txt, setup.py
- fixed types to use python >3.5 style
- fixed type errors
- added stage to travis to check types using pytype
=> Add Type checks

CHANGELOG.rst, rasa_sdk/executor.py
- Replace the `CollectingDispatcher` methods with a single method. The former structure was based on the sdk's interactin with rasa_core and is no longer necessary.
Related to https://github.com/RasaHQ/rasa/pull/4687
(Guess I should also update the changelog there)
=> Dispatcher methods

CHANGELOG.rst
=> add missing backticks

CHANGELOG.rst, rasa_sdk/executor.py
- use FutureWarnings based on suggestion [here](https://docs.python.org/3/library/exceptions.html#FutureWarning) as the warnings are intended for end users
=> Show and improve deprecation warnings

CHANGELOG.rst, rasa_sdk/executor.py, tests/test_executor.py
- make 'text' the first positional argument in `utter_message`
- fix `utter_elements`
- return empty list instead of None for buttons + elements
=> Utter fixes

rasa_sdk/knowledge_base/actions.py
- Use utter_message as recommended. Will also update the example bots in rasa to that effect
=> use utter_message as recommended

CHANGELOG.rst, rasa_sdk/events.py
=> SessionStarted event

CHANGELOG.rst
=> Prepare 1.6.1

.gitignore, pip-wheel-metadata/rasa_sdk.dist-info/LICENSE.txt, pip-wheel-metadata/rasa_sdk.dist-info/METADATA, pip-wheel-metadata/rasa_sdk.dist-info/top_level.txt, rasa_sdk/forms.py, rasa_sdk/knowledge_base/actions.py, tests/knowledge_base/test_actions.py, tests/test_forms.py
- add async action support to forms and kb
=> make forms and kb async compatible

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.rst, Makefile, README.md, changelog/.gitignore, changelog/README.md, dev-requirements.txt, pyproject.toml, rasa_sdk/version.py, scripts/release.py
- add towncrier for changelog management
- added a release script
=> added towncrier for changelog management

README.md, changelog/149.misc.rst
- Add "Building from source" section to README.md
=> Add "Building from source" section to README.md

CHANGELOG.rst, changelog/130.improvement.rst, changelog/145.improvement.rst, changelog/148.misc.rst, changelog/149.misc.rst, rasa_sdk/version.py
=> prepared release of version 1.8.0

changelog/153.bugfix.rst, poetry.lock, pyproject.toml
=> Make it possible to use `requests` library inside actions.

CHANGELOG.rst, changelog/153.bugfix.rst, pyproject.toml, rasa_sdk/version.py
=> Prepare release 1.8.1

CHANGELOG.rst, changelog/110.bugfix.rst, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 1.9.0

CHANGELOG.rst, changelog/3765.feature.rst, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 1.10.0-alpha1

.github/workflows/vulnerability-scan.yml, Dockerfile, changelog/176.bugfix.rst, changelog/176.improvement.rst, poetry.lock
- update Docker images to use Python 3.7
- update app dependencies to fix security vulnerability  CVE-2020-1747
- add regular scan for security issues
- sdk part of https://github.com/RasaHQ/rasa-x/issues/2366
=> security scan + security fixes

.github/workflows/vulnerability-scan.yml
- use modified github action which updates an issue in case there is already an existing one
- only run check every third day
- related to https://github.com/homoluctus/gitrivy/pull/62
- fail if vulnerability was found
=> no trivy duplicate issues

CHANGELOG.rst, changelog/164.feature.rst, changelog/176.bugfix.rst, changelog/176.improvement.rst, changelog/3765.feature.rst, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 1.10.0

.github/workflows/continous-integration.yml
- Fix GITHUB_TAG var in workflow
=> strip ref/tags/ from GITHUB_TAG var in workflow

pyproject.toml, rasa_sdk/version.py
=> bump version to 2.0a1

rasa_sdk/executor.py, rasa_sdk/interfaces.py
- Fixed typo in method documentation
=> updated typo in docs

README.md
- apparently people actually read this README because it's on pypi
- [x updated the documentation
=> update docker instructions with permissions

CHANGELOG.rst, changelog/212.bugfix.rst, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 1.10.1

rasa_sdk/endpoint.py
- Make it clear that the server is ready and isn't hanging (there used to be a log to this effect, so now users are confused when it doesn't appear) 
- fix https://github.com/RasaHQ/rasa/issues/4971
=> re-add 'up and ready' log

CHANGELOG.rst, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 1.10.2

pyproject.toml, rasa_sdk/version.py
- Version bump for upcoming release of Rasa Open Source alpha2
=> prepared release of version 2.0.0a2

rasa_sdk/endpoint.py, rasa_sdk/executor.py, rasa_sdk/forms.py, rasa_sdk/interfaces.py
- Remove any non-debug logs that could feasibly contain PII. 
- Turn `Failed to extract slot email with action subscribe_newsletter_form` into a debug log because it is expected behavior for unexpected input, and clarify that in the log to make it less confusing.
=> remove pii from non-debug logs

pyproject.toml, rasa_sdk/version.py
=> Prepared release of version 2.0.0a3

pyproject.toml, rasa_sdk/version.py
=> Prepared release of version 2.0.0a4

changelog/265.misc.md, poetry.lock, pyproject.toml, rasa_sdk/executor.py, rasa_sdk/forms.py, rasa_sdk/interfaces.py, rasa_sdk/knowledge_base/actions.py, tests/test_forms.py, tests/test_tracker.py
Updates sanic + some dev dependencies for Rasa X
=> Dependency updates (sanic & other stuff)

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 2.0.0a5

pyproject.toml, rasa_sdk/version.py
=> Prepared release of version 2.0.0rc1

CHANGELOG.rst, changelog/237.enhancement.rst, pyproject.toml, rasa_sdk/version.py
=> Prepare release 1.10.3

CHANGELOG.mdx, changelog/237.improvement.md, rasa_sdk/forms.py, tests/test_forms.py
=> Merge 1.10.x into master

scripts/push_docs_to_branch.sh
- Relates to https://github.com/RasaHQ/rasa/issues/6620
- We forgot to update the docs release script of the SDK 😅 
=> more granular updates in docs release script

changelog/280.bugfix.md, rasa_sdk/interfaces.py, tests/test_tracker.py
=> fix event type used in applied events function

rasa_sdk/forms.py
- During validation, the slots dict can change, so need to allow for this.
=> Fix loop over slots to allow changes of the slots dict

rasa_sdk/forms.py
- Turn log for no validation function into debug log -- UserWarnings are for things we want the user to fix -- there is actually no problem with not providing a validation function
=> make no validation function log debug

.github/workflows/continous-integration.yml, .github/workflows/documentation.yml, .github/workflows/vulnerability-scan.yml
Resolves https://github.com/RasaHQ/rasa-x/issues/3668
=> Don't use set-env for the CIs

.github/workflows/security-scans.yml
Use gitleaks for detecting hardcoded secrets, https://github.com/RasaHQ/rasa-x/issues/3624
=> Use gitleaks for detecting hardcoded secrets

scripts/push_docs_to_branch.sh
- Support duplicate tag pushes in the docs release mechanism (it led to this silent issue: https://github.com/RasaHQ/rasa/runs/1226850034?check_suite_focus=true)
- relates to RasaHQ/rasa#7028
=> docs update mechanism supports duplicate versions

scripts/push_docs_to_branch.sh
- Relates to https://github.com/RasaHQ/rasa/pull/7074
=> avoid duplicating docs/ folder when releasing micros

Makefile
- SDK followup of https://github.com/RasaHQ/rasa/pull/7157/files
=> pydocstyle: only validate changes of branch

.github/workflows/continous-integration.yml, .github/workflows/documentation.yml
- Update the setup-poetry GH action to v4
=> Update the setup-poetry GH action to v4

.github/workflows/security-scans.yml
- Run the gitleaks scan only on a pull request event
=> Run the gitleaks scan only on a pull request event

.github/workflows/continous-integration.yml, Makefile
- followup from https://github.com/RasaHQ/rasa/pull/7242
- check the correct path `rasa_sdk` (not `rasa-sdk`)
=> fix pydocstyle

.github/workflows/continous-integration.yml
- add quotes in case branch names start with '#'
=> add quotes in case branch names start with '#'

.github/workflows/security-scans.yml
- Fixes https://github.com/RasaHQ/rasa/issues/7180
=> use another GH action to cancel workflow runs

CHANGELOG.mdx, changelog/344.bugfix.md, pyproject.toml, rasa_sdk/version.py
- micro release to fix the critical bug in `FormValidationAction`
=> prepared release of version 2.1.1

.github/workflows/documentation.yml
- Update the ssh-agent GH action
=> Update the ssh-agent GH action

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 2.1.2

docs/docs/sdk-actions.mdx
@erohmensing per our ping on slack yesterday, the example will now also show the type imports.
=> Small docs fix. 

pyproject.toml, rasa_sdk/version.py
I didn't make any changes, but need the release to release 2.2.0a1 of rasa open source
- [] added some tests for the functionality
- [] updated the documentation
- [] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/master/changelog) for instructions)
=> prepared release of version 2.2.0a1

.github/workflows/spellcheck.yml
=> typoci action

.github/workflows/continous-integration.yml
=> Adding pep440_version_utils to release dependencies

docs/docs/sdk-dispatcher.mdx
Proposed changes:
-  Typos to be fixed
-  updation in the documentation
Status (please check what you already did):
- made PR ready for code review
- added some tests for the functionality
- updated the documentation
- updated the changelog (please check changelog for instructions)
- reformat files using black (please check Readme for instructions)
=> All mentioned typos fixed

docs/static/spec/rasa.yml
- Update spec for Slots & Responses to match Rasa Open Source's request to actions server
=> Update Actions Server Spec for Slots & Responses

setup.cfg
- ignore missing docstrings for magic methods
=> ignore missing docstrings for magic methods

CHANGELOG.mdx, changelog/1234.bugfix.md, poetry.lock, pyproject.toml, rasa_sdk/version.py
- don't pin `uvloop` for Windows
=> Prepare release 2.3.1

changelog/419.bugfix.md, poetry.lock, pyproject.toml
- fix https://github.com/RasaHQ/rasa-sdk/issues/395
- update dependencies
=> Missing `typing_extensions` module and dependency updates

Makefile
- add `poetry run python -m pip install -U pip` to the Makefile in order to install the latest version of pip before installing any dependencies (the same is done in both `rasa` and `rasa-x`)
=> Add pip upgrade command to the Makefile

CHANGELOG.mdx, changelog/419.bugfix.md, changelog/8223.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 2.4.1

.github/dependabot.yml
- update dependabot `reviewers` section to assign random reviewers from enable squad instead of just me :)
=> Update dependabot `reviewers` from `alwx` to `RasaHQ/enable-squad`

CHANGELOG.mdx, changelog/376.misc.md, pyproject.toml, rasa_sdk/version.py
- prepared release of version 2.5.0
=> prepared release of version 2.5.0

.github/workflows/continuous-integration.yml
- Use correct name for Docker HUB user
=> Use secrets instead of env variable

rasa_sdk/interfaces.py
- Add type hint for `Action.run`'s `dispatcher` argument
=> add type hints for dispatcher in Action

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 2.7.0

.github/workflows/vulnerability-scan.yml
lazy-actions/gitrivy#62 was merged. We can switch back to upstream.
=> Switch back to upstream lazy-actions/gitrivy

CHANGELOG.mdx, changelog/441.improvement.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 2.8.0

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
-  Update urllib3 to 1.26.5 to fix CVE-2021-33503
=> prepared release of version 2.8.1

CHANGELOG.mdx, changelog/499.misc.md
- Update urllib3 to 1.26.5 to fix CVE-2021-33503. See #504 
=> Prepare release 2.8.1

.github/workflows/continuous-integration.yml
- Do not fail if a Python package distribution exists in the target package index
=> Do not fail if a Python package distribution exists in the target package index

.github/workflows/continuous-integration.yml, changelog/501.removal.md, poetry.lock, pyproject.toml, rasa_sdk/endpoint.py, tests/conftest.py
- fixes #501 
- fixes #500 by updating sanic to > 21.0.0
- fixes #503 
=> 501 drop py36 support

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
prepared release of version 2.8.2
=> prepared release of version 2.8.2

.github/workflows/continuous-integration.yml, CHANGELOG.mdx, poetry.lock, pyproject.toml, rasa_sdk/version.py
=> Merge 2.8.2 main

poetry.lock, pyproject.toml, rasa_sdk/version.py
prepared release of version 3.0.0rc1
=> prepared release of version 3.0.0rc1

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.0.0rc3

docs/docs/actions.mdx, docs/docs/knowledge-base-actions.mdx, docs/docs/validation-action.mdx, docs/sidebars.js
=> Update Action Server docs with slot validation actions

CHANGELOG.mdx, changelog/501.removal.md, changelog/529.improvement.md, pyproject.toml, rasa_sdk/version.py
Prepared release of version 3.0.0
=> Prepared release of version 3.0.0

CHANGELOG.mdx, changelog/609.misc.md, pyproject.toml, rasa_sdk/version.py
- Update linux-libc-dev package to close #609 
=> prepared release of version 2.8.3

.github/workflows/continuous-integration.yml, .github/workflows/documentation.yml, docs/docs/deploy-action-server.mdx, docs/sidebars.js
- Add a deployment method to the docs
=> Add a deployment method to the docs

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
- prepared release of version 3.0.1
- The docs update
=> prepared release of version 3.0.1

.github/workflows/documentation.yml, docs/package.json, docs/yarn.lock, scripts/push_docs_to_branch.sh
-  Update documentation workflow to only publish one version per major
=> Update documentation workflow to only publish one version per major

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> Prepare release 3.0.2

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> Prepare release 3.0.3

.github/change_filters.yml, .github/workflows/documentation.yml
- Fixes https://github.com/RasaHQ/rasa/issues/10707
=> Disable docs preview workflow on PRs coming from forks

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
- micro change to ensure `rasa shell` runs correctly.
=> prepared release of version 3.0.4

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
- micro change to bump `sanic` to v21.12 matching `rasa`
=> prepared release of version 3.0.5

docs/versioned_sidebars/version-3.x-sidebars.json
=> 3.0.5 docs - update sidebar

changelog/719.bugfix.md, poetry.lock, pyproject.toml
- Remove uvloop pin (related to https://github.com/RasaHQ/rasa/pull/10684)
=> build: remove `uvloop` pin

CHANGELOG.mdx, changelog/719.bugfix.md, changelog/_template.md.jinja2, pyproject.toml, rasa_sdk/version.py, scripts/release.py
=> Prepare release 3.0.6

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.1.0

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> Prepare release 2.8.5

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
- Releasing a new version of the SDK in order to update the docs
=> prepared release of version 3.1.2

scripts/push_docs_to_branch.sh
- Address workflow issue here: https://github.com/RasaHQ/rasa-sdk/runs/6792682974?check_suite_focus=true
- Simply copy what we do in Rasa OSS
=> Make docs workflow more resilient

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.2.0

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> Prepare release 2.8.8

poetry.lock
- Part of fix required for [ATO-299](https://rasahq.atlassian.net/browse/ATO-299)
=> Update Sanic and ujson to latest patches on 3.2.x

poetry.lock
- Part of fix required for [ATO-299](https://rasahq.atlassian.net/browse/ATO-299)
- Note that `ujson` is already updated to `5.4.0` in `poetry.lock` [here](https://github.com/RasaHQ/rasa-sdk/blob/b35df893baf4aac3cfdc8986fad8ce67ac917d51/poetry.lock#L747)
=> Update Sanic to latest patch on 2.8.x

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> Prepare release 2.8.9

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.0.7

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.2.1

.github/workflows/security-scans.yml, Dockerfile
- Add Trivy secret scanning for detecting hardcoded secrets.
=> Add Trivy secret scanning

.github/workflows/security-scans.yml, trivy-secret.yaml
- Adds Trivy ignore file for false positive secrets.
- Fails builds if a secret is found.
- Provides instructions to devs as to how to proceed in the build output.
=> Improve Trivy Configuration

.github/poetry_version.txt, .github/workflows/continuous-integration.yml, .github/workflows/documentation.yml, Dockerfile, README.md, changelog/884.misc.md, poetry.lock, pyproject.toml
- Updated Poetry version used in the CI to latest version (1.2.2)
- Updated `typing-extensions`
=> Required upgrades in preparation for Python 3.10 support

CHANGELOG.mdx, changelog/877.improvement.md, changelog/884.misc.md, changelog/888.improvement.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.4.0

.github/workflows/continuous-integration.yml, Dockerfile, Makefile, changelog/929.improvement.md, rasa_sdk/endpoint.py, tests/test_endpoint.py
Add capability to handle deflated body of a HTTP request.
=> [ATO-711] Port handle deflated webhook request to 3.2.x

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.5.0a2.dev1

.github/workflows/continuous-integration.yml
- Replace `set-output` deprecated command
=> Replace `set-output` deprecated command

.github/workflows/security-scans.yml
- Add a Snyk scan to monitor Python dependencies.
=> Add Snyk scan for Python deps

changelog/930.improvement.md, rasa_sdk/constants.py, rasa_sdk/endpoint.py, tests/test_endpoint.py
Add capability to handle deflated body of a HTTP request.
=> [ATO-712] Port deflate custom action request to 3.3.x

rasa_sdk/endpoint.py
If decompression of an HTTP body for custom action fails return a 400 with a descriptive message.
=> Return a 400 response if an error occurs during decompression of an HTTP body

.github/workflows/continuous-integration.yml, .github/workflows/security-scans.yml, .github/workflows/semgrep-check.yml
- Replace version number with commit SHA
=> Replace version number with specific commit SHA in gh actions

CHANGELOG.mdx, changelog/929.improvement.md, pyproject.toml, rasa_sdk/version.py
- Prepare SDK release for 3.2.3
- https://rasahq.atlassian.net/browse/ATO-729
=> ATO-729 prepared release of version 3.2.3

CHANGELOG.mdx, changelog/877.improvement.md, changelog/884.misc.md, changelog/888.improvement.md, changelog/930.improvement.md, poetry.lock, pyproject.toml, rasa_sdk/version.py
- Release 3.3.1
- https://rasahq.atlassian.net/browse/ATO-730
=> ATO-730 Prepare release 3.3.1

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.5.0b1

.github/workflows/continuous-integration.yml, .github/workflows/security-scans.yml, .github/workflows/semgrep-check.yml, .github/workflows/spellcheck.yml, Dockerfile
- Upgrade Dockerfile base image to Ubuntu 22.04
- Remove `latest` tag from Github runners
=> Upgrade Ubuntu to 22.04 and remove latest runner tag

.github/workflows/continuous-integration.yml, .github/workflows/security-scans.yml, .github/workflows/semgrep-check.yml, .github/workflows/spellcheck.yml, Dockerfile
=> Merge 3.4.x to main

.github/workflows/continuous-integration.yml, .github/workflows/security-scans.yml, .github/workflows/semgrep-check.yml
- Fix warning - Github Actions Node 12.x Deprecation by Summer 2023
=> Bump Github Actions dependencies

poetry.lock, pyproject.toml
Updated: 
- [typing-extensions](https://github.com/RasaHQ/rasa-sdk/pull/944)
- [mypy](https://github.com/RasaHQ/rasa-sdk/pull/951/files)
=> Upgrade dependencies (housekeeping)

poetry.lock, pyproject.toml
=> fix ImportError from Sanic, Websockets

poetry.lock
- Port fix from 3.5.x
https://github.com/RasaHQ/rasa-sdk/pull/959
=> add constraint on websockets library

poetry.lock
- Ports changes from https://github.com/RasaHQ/rasa-sdk/pull/959 to 3.4.x
=> Add constraints to websockets library for 3.4.x

CHANGELOG.mdx, changelog/959.misc.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.5.1

poetry.lock, pyproject.toml
=> Dependency Upgrades (Sprint 44)

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.7.0b1

poetry.lock, pyproject.toml
=> Dependency upgrades 47

CHANGELOG.mdx, changelog/1219.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.6.1

CHANGELOG.mdx, changelog/1219.bugfix.md, pyproject.toml, rasa_sdk/plugin.py, rasa_sdk/version.py, tests/test_plugin.py
* fix: logger message to debug when plugins not found
* add changelog and test
* fix:lint error
* fix:lint error
* amend test and log format
---------
Co-authored-by: Anca Lita <27920906+ancalita@users.noreply.github.com>
(cherry picked from commit 2caaa67cae3de2a385932ecd370cccdfe712a51a)
- ...
=> Port latest changes from 3.6.x

.github/workflows/scan_docker_image_dependencies.yml
- Adds scheduled dependency scanning and alerting as in Rasa Plus.
=> Add Dependency Scanning & Alerting

.github/workflows/scan_docker_image_dependencies.yml
- Disable scheduled scans in a trial to use the Snyk Jira integration instead.
=> Disable Scheduled Dependency Scan

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.8.0a1

changelog/1026.bugfix.md, poetry.lock, pyproject.toml
- Fixes [ATO-1420](https://rasahq.atlassian.net/browse/ATO-1420)
[ATO-1420]: https://rasahq.atlassian.net/browse/ATO-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix security vulnerabilities

CHANGELOG.mdx, changelog/1026.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.6.2

poetry.lock, pyproject.toml
=> Dependencies upgrades 53

poetry.lock
- Bump Certifi as per https://rasahq.atlassian.net/browse/ATO-1662
=> [3.6.x] bump certifi

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.7.0rc1

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.7.0rc2

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.7.0rc3

rasa_sdk/endpoint.py
- suppressed deprecation warnings from site packages (sanic)
=> [ENG-669] Remove deprecation warnings

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.7.0rc4

CHANGELOG.mdx, changelog/1016.feature.md, pyproject.toml, rasa_sdk/version.py
=> Prepare release 3.7.0

CHANGELOG.mdx, changelog/1016.feature.md, pyproject.toml, rasa_sdk/endpoint.py, rasa_sdk/version.py
=> Merge 3.7.x to main

pyproject.toml, rasa_sdk/version.py
Needed for sharing the first experimental version of fixing flow scalability with our customers.
=> Prepared release of version 3.8.0b1.dev1

.dockerignore, .github/workflows/security-patching.yml, Dockerfile.patch, scripts/get_tags_from_branch.py
- Adds automated security patching for Rasa Pro users.
=> Add Automated Security Patching

changelog/1054.bugfix.md, poetry.lock
- Fixes [ATO-1938](https://rasahq.atlassian.net/browse/ATO-1938)
[ATO-1938]: https://rasahq.atlassian.net/browse/ATO-1938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Port Certifi vulnerability fix - main

CHANGELOG.mdx, changelog/1055.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.7.1

changelog/1060.improvement.md, poetry.lock, pyproject.toml, tests/test_endpoint.py
- Fixes [ATO-887](https://rasahq.atlassian.net/browse/ATO-887)
[ATO-887]: https://rasahq.atlassian.net/browse/ATO-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ATO-887] Port sanic and sanic-testing upgrades

changelog/1060.improvement.md, poetry.lock, pyproject.toml, tests/test_endpoint.py
=> Revert "[ATO-887] Port sanic and sanic-testing upgrades"

changelog/1063.bugfix.md, rasa_sdk/endpoint.py, tests/test_plugin.py
- Fixes a part of [ATO-2016](https://rasahq.atlassian.net/browse/ATO-2016)
[ATO-2016]: https://rasahq.atlassian.net/browse/ATO-2016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ATO-2016] Fix App Instantiation Error

changelog/1063.bugfix.md, rasa_sdk/endpoint.py, tests/test_plugin.py
Reverts RasaHQ/rasa-sdk#1063
Fixes a part of [ATO-2142](https://rasahq.atlassian.net/browse/ATO-2142)
[ATO-2142]: https://rasahq.atlassian.net/browse/ATO-2142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "[ATO-2016] Fix App Instantiation Error"

changelog/1057.improvement.md, poetry.lock, pyproject.toml, tests/test_endpoint.py
Reverts https://github.com/RasaHQ/rasa-sdk/pull/1057
Fixes a part of [ATO-2142](https://rasahq.atlassian.net/browse/ATO-2142)
[ATO-2142]: https://rasahq.atlassian.net/browse/ATO-2142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "[ATO-887] Upgrade Sanic and Sanic-testing"

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.8.0rc1

.github/workflows/continuous-integration.yml
- port https://github.com/RasaHQ/rasa-sdk/pull/1087
=> Update slack release notifications channels

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.8.0rc2

.github/workflows/git-backup.yml
=> Add backup to s3

CHANGELOG.mdx, changelog/1054.bugfix.md, changelog/1072.improvement.md, changelog/1073.improvement.md, changelog/1074.improvement.md, changelog/1075.improvement.md, changelog/1076.improvement.md, changelog/1077.improvement.md, changelog/1078.improvement.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.8.0

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.9.0.dev1

CHANGELOG.mdx, changelog/1103.misc.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.9.0.dev2

rasa_sdk/endpoint.py, rasa_sdk/executor.py, rasa_sdk/interfaces.py, tests/test_endpoint.py, tests/tracing/instrumentation/test_tracing.py
- Checks the domain in the payload and return 449 status code if the domain is missing (both stored and in the payload) or stale (digest mismatch).
=> Domain Payload Optimization to Action server

pyproject.toml, rasa_sdk/version.py
- First release candidate for 3.9.0
=> prepared release of version 3.9.0rc1

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.9.0rc2

pyproject.toml, rasa_sdk/version.py
- Pre release version 3.9.0rc3
=> prepared release of version 3.9.0rc3

CHANGELOG.mdx, changelog/1109.feature.md, changelog/1113.misc.md, changelog/1117.bugfix.md, changelog/1120.misc.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.9.0

.github/PULL_REQUEST_TEMPLATE.md, Makefile, README.md, changelog/1131.misc.md, poetry.lock, pyproject.toml, rasa_sdk/executor.py, rasa_sdk/interfaces.py, rasa_sdk/knowledge_base/actions.py, rasa_sdk/knowledge_base/storage.py, rasa_sdk/knowledge_base/utils.py, rasa_sdk/tracing/endpoints.py, rasa_sdk/tracing/tracer_register.py, rasa_sdk/types.py, rasa_sdk/utils.py, tests/knowledge_base/test_actions.py, tests/test_forms.py, tests/test_interfaces.py, tests/tracing/conftest.py, tests/tracing/instrumentation/conftest.py, tests/tracing/instrumentation/test_action_executor.py, tests/tracing/instrumentation/test_form_validation_action.py, tests/tracing/instrumentation/test_tracing.py, tests/tracing/instrumentation/test_validation_action.py, tests/tracing/test_utils.py
Update `ruff` to 0.3.7
Use `ruff` as code formatter.
Some files had to be reformatted.
A few lines of code needed to be updated to follow the linter rules.
=> Update ruff to 0.3.7 on 3.8.x

CHANGELOG.mdx, changelog/1123.misc.md, changelog/1129.bugfix.md, changelog/1130.misc.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.9.1

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.10.0rc1

pyproject.toml, rasa_sdk/version.py
- ...
-    N/A
-    N/A
-    N/A
=> Prepared RC2: 3.10.0rc2

.github/workflows/tag-release.yml
=> ENG-1235: Fix release tagging workflow, by calling correct Make target

CHANGELOG.mdx, changelog/1122.improvement.md, changelog/1128.misc.md, changelog/1135.misc.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.10.0

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.11.0.dev1

CHANGELOG.mdx, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.10.1

Makefile
[Jira task](https://rasahq.atlassian.net/browse/INFRA-1019)
- Push release docker image to GCP artifact registry with [version]-latest tag
=> [INFRA-1019] Push image with [version]-latest tag

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.11.0rc1

.github/workflows/release-artifacts.yml
[Jira task](https://rasahq.atlassian.net/browse/INFRA-1116)
- Use `github-notifications` app for slack notifications
- Format slack notification messages
=> [INFRA-1116] Slack notifications improvement

.github/actions/setup-python-env/action.yml, .github/workflows/release.yml
[Jira task](https://rasahq.atlassian.net/browse/INFRA-1118)
- On workflow dispatch after entering release version number the script will:
- Checkout code
- Setup Python Environment
- Prepare the release using input version
- ensure_clean_git()
- version = next_version(args)
- confirm_version(version)
- write_version_file(version)
- write_version_to_pyproject(version)
- generate_changelog(version)
- create_commit(version)
- push_changes()
- print_done_message_same_branch(version)
- Create a pull request
=> [INFRA-1118] Add workflow dispatch for release workflow

.github/workflows/continuous-integration.yml
=> Add skip condition for prepare-release branches

.github/workflows/release-artifacts.yml
=> Edit rassabot token name

.github/workflows/release-artifacts.yml
=> Update rasa bot token name

scripts/publish_gh_release_notes.py
- Add dev builds to release notes python script
=> [INFRA-1152] Fix publish release notes step

.github/workflows/continuous-integration.yml, .github/workflows/dev-release.yml, .github/workflows/git-backup.yml, .github/workflows/pr-cleanup.yml, .github/workflows/pr-merged.yml, .github/workflows/release-artifacts.yml, .github/workflows/release.yml, .github/workflows/scan_docker_image_dependencies.yml, .github/workflows/security-patching.yml, .github/workflows/security-scans.yml, .github/workflows/semgrep-check.yml, .github/workflows/spellcheck.yml, scripts/publish_gh_release_notes.py
[JIRA](https://rasahq.atlassian.net/browse/INFRA-1152)
- align release workflows with main branch
=> [INFRA-1152] Fix release workflows on 3.9.x

.github/actions/setup-python-env/action.yml, .github/workflows/continuous-integration.yml, .github/workflows/release.yml
Update `actions/cache` to `actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57` (version 4.2.0).
=> Update actions/cache to 4.2.0

.github/workflows/release-artifacts.yml
[JIRA](https://rasahq.atlassian.net/browse/INFRA-1159)
Tested here: https://github.com/RasaHQ/rasa-sdk/actions/runs/13114794521/job/36586361702
=> [INFRA-1159] Release Docker images to both GCP and DockerHub

pyproject.toml, rasa_sdk/version.py
- 3.12.0dev1 to create corresponding version in rasa-pro
=> prepared release of version 3.12.0.dev1

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.12.0.dev2

CHANGELOG.mdx, changelog/1145.improvement.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.12.0

pyproject.toml, rasa_sdk/version.py
- Dev release `3.13.0.dev1` created to enable a corresponding dev release on rasa-private
=> prepared release of version 3.13.0.dev1

.github/workflows/continuous-integration.yml
=> Add workflow displatch on CI to trgigger main and build docker images

CHANGELOG.mdx, changelog/1230.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.12.1

CHANGELOG.mdx, changelog/1229.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.11.2

CHANGELOG.mdx, changelog/1228.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.10.2

CHANGELOG.mdx, changelog/1216.misc.md, changelog/1227.bugfix.md, pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.13.0

.github/workflows/release-artifacts.yml
- port https://github.com/RasaHQ/rasa-sdk/pull/1239 into main
=> Update slack notification channel to #prodeng-internal

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.14.0.dev1

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.14.0.dev2

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.14.0.dev3

pyproject.toml, rasa_sdk/version.py
- https://rasahq.atlassian.net/browse/ENG-2223
=> prepared release of version 3.14.0.dev4

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.14.0.dev6

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.14.0.dev7

pyproject.toml, rasa_sdk/version.py
- Ticket: https://rasahq.atlassian.net/browse/ENG-2386
=> prepared release of version 3.14.0.dev8

pyproject.toml, rasa_sdk/version.py
=> prepared release of version 3.14.0rc1
