RasaHQ/rasa-sdk

CHANGELOG.rst
rasa_core_sdk/forms.py

-  `validate()` function calls optionally `validate_{slot_name}` functions to validate slot values
- `validate_{slot_name}` returns None for invalid values

Validate methods for slots

---

rasa_core_sdk/endpoint.py
rasa_core_sdk/utils.py

- *Added coloredlogs to the SDK.* I assume I just had to add it where the \_\_main__ gets called, since all the files are getting their logger from the line 'logger = logging.getLogger(\_\_name__)" so I just imported the utils from rasa and added the same lines that are in the rasa_core library. It worked for me.

Added coloredlogs to the SDK

---

CHANGELOG.rst
rasa_core_sdk/forms.py
tests/test_forms.py

If a slot could not be validated properly, we may want to deactivate the form immediately (e.g. without submitting).  Currently, adding `self._deactivate()` to the events would still cause the rest of the `run()` method to continue.
- Add a check in the `run()` method that we didn't already try to deactivate
- Rename method to `deativate()` (i.e. remove the "protected" status)

Allow for early form deactivation during validation

---

CHANGELOG.rst
rasa_core_sdk/__init__.py
rasa_core_sdk/events.py
tests/test_tracker.py

I just realized that the `tracker.get_latest_input_channel` feature I've had in my fork for a while is not part of the official `rasa_core_sdk` yet (but is part of `rasa_core`). Because there's been multiple requests about this on the forum (e.g. [here](https://forum.rasa.com/t/how-to-detect-chat-platform-in-actions-py/2991/8) or [here](https://forum.rasa.com/t/action-latest-action-name-followup-action-latest-input-channel-return-none/4157)) I wanted to push this change.
- Similar to `rasa_core`'s approach, we reverse traverse tracker.events until latest `user` event is found. Then return `event.input_channel` 

added latest_input_channel to tracker

---

rasa_core_sdk/forms.py
tests/test_forms.py

- Modified `validate` function to validate all extracted slots. Previously it validates only requested slot but not extracted other slots.

Validate for all extracted slots

---

rasa_core_sdk/executor.py
rasa_core_sdk/utils.py

- move `Element` and `Button` classes to sdk utils so that anyone using these classes in custom actions can still import them
- remove possible deprecation of utter_button_template since it's useful for cases in which the button payloads are written in a custom action (see medicare bot)

re-add Element and Button classes from rasa.core.dispatcher

---

rasa_sdk/interfaces.py

- The current `tracker` checks for a restart event by comparing against `restarted`, change it to ~~`action_restart`~~ `restart`

Correct the latest restart index from events

---

rasa_sdk/executor.py

- When trying to send image from custom actions there is no function in the dispatcher to send image as a URL. But in rasa core, it supports the image sending and only needs to send image url formated as {"image" : image_url }. Added utter_image_url function and implementation to CollectingDispatcher class. 
- [+] made PR ready for code review
- [- ] added some tests for the functionality
- [- ] updated the documentation
- [- ] updated the changelog

add utter_image_url

---

rasa_sdk/forms.py

- slots of the real tracker get populated after execution of an action, so logging of slots should be performed on `temp_tracker`

print slots from temp_tracker before submit

---

rasa_sdk/forms.py
rasa_sdk/knowledge_base/actions.py

- change deprecated `utter_template` calls to `utter_message`

change deprecated `utter_template` calls to `utter_message`

---

CHANGELOG.rst
changelog/130.improvement.rst
rasa_sdk/interfaces.py
tests/test_tracker.py

The Rasa tracker class implements the convenience methods `last_executed_action_has`, `get_last_event_for` and `applied_events`. This PR simply copies over this functionality from Rasa.

implement additional tracker methods

---

changelog/110.bugfix.rst
changelog/153.bugfix.rst
rasa_sdk/executor.py
tests/test_endpoint.py

**Issue**:
In cases, when the actions.py or the actions directory is missing, rasa throws ImportError excption but does not terminate the process and the action keeps running, as metioned #110 
Adding sys.exit(1) right after Import Error in register_package().
**Status**:

Server should not start if module not found

---

rasa_sdk/forms.py
tests/test_forms.py

Use the custom slot mapping 'from_entity' defined by the user to fill other slots.
Will be merged into `composite-entities`. We gonna collect some user feedback before we actually gonna merge this into master.

Use custom mapping "from_entity" to fill other slots

---

.gitignore
changelog/164.feature.rst
rasa_sdk/__main__.py
rasa_sdk/cli/arguments.py
rasa_sdk/endpoint.py
rasa_sdk/executor.py
setup.cfg
tests/test_actions.py
tests/test_endpoint.py
tests/test_executor.py

- Add a new CLI argument, `--auto-reload`. If enabled, modules containing actions will be reloaded when an HTTP request is received, but only if the files have been changed since they were last loaded.
- Closes https://github.com/RasaHQ/rasa/issues/4058.
Implementation details:
When we load a regular package (directory with `__init__.py` inside), or a file module (e.g. `actions.py`), the file path and last-modified timestamp is recorded. Whenever an HTTP request is received, before running the actions, all current file timestamps are checked against the recorded ones (there is no polling or file modification events involved). This process is quick because it only involves comparing floats. All files that have been modified since the last check are re-loaded using …

Add auto-reload upon file timestamp change

---

.github/workflows/continous-integration.yml
scripts/publish_gh_release_notes.py

- Reuse [`publish_gh_release_notes.py` script from rasa](https://github.com/RasaHQ/rasa/blob/master/scripts/publish_gh_release_notes.py)
- Run it in workflow
**This PR needs...**:

create github releases when pushing tags

---

changelog/212.bugfix.rst
rasa_sdk/executor.py
tests/test_executor.py

Fix `ActionExecutor` class sometimes not loading some `Action` subclasses, in cases where a user-defined action inherited from another user-defined action.
Closes https://github.com/RasaHQ/rasa-sdk/issues/204/.

Fix ActionExecutor not loading some subclasses of Action

---

changelog/237.enhancement.rst
rasa_sdk/forms.py
tests/test_forms.py

Only fill other slots if slot mapping contains a role or group restriction.
related to [forum post](https://forum.rasa.com/t/same-training-data-for-multiple-entities-issue/31285/5
)
closes #218 

Only fill other slots if slot mapping contains a group/role restriction

---

changelog/239.improvement.rst
rasa_sdk/forms.py
rasa_sdk/interfaces.py
tests/test_forms.py

- add that form needs to validate if active_form dict is empty, because it means it is first form call
- fixes https://github.com/RasaHQ/rasa-sdk/issues/80

allow validating user input on activation even if there are actions in between input and form

---

changelog/238.feature.rst
rasa_sdk/interfaces.py
tests/test_tracker.py

- fix https://github.com/RasaHQ/rasa-sdk/issues/238
- add a method `form_slots_to_validate` to `Tracker` to make it easier to retrieve extracted slot candidates from a form

add helper to extract form slot candidates

---

changelog/280.bugfix.md
rasa_sdk/interfaces.py
tests/test_tracker.py

The `applied_events` function was using the event name instead of the event type when checking if an event was a `restart`, `rewind` or `undo`. This PR fixes #280.

Fix event type used in applied events function

---

changelog/6463.improvement.md
changelog/6463.removal.md
rasa_sdk/events.py
rasa_sdk/forms.py
tests/test_events.py
tests/test_forms.py

- SDK part of https://github.com/RasaHQ/rasa/issues/6463
- `FormValidation` was renamed in Rasa Open Source. It's now called `LoopInterrupted`. 
- deprecate `FormValidation`
- add support for `LoopInterrupted` event
- adapt legacy `FormAction` to use `is_interrupted` instead of old `validate` key

add support for `LoopInterrupted` event

---

changelog/294.improvement.md
rasa_sdk/forms.py
tests/test_forms.py

- update `FormValidationAction` to automatically replace `-` with `_` in slot name for validation function (based on 2.0 feedback)

Update `FormValidationAction` to replace `-` with `_` in slot name

---

docs/netlify.toml
docs/package.json
docs/static/_redirects

This PR changes the build path of the `docusaurus build` command to match the subpath configured as `baseUrl` in `docusarus.config.js`. Doing this avoids the additional rewrite of sub-directory paths back to the root, and enables content 301 redirections to be maintained in this repo, rather than in `rasa-website`.
This corresponds to [this PR on rasa-website](https://github.com/RasaHQ/rasa-website/pull/864), which should be merged first.
NOTE: the `/docs/static/_redirects` file has been replaced by a `/docs/netlify.toml` instead, because due to the changed build path it would now end up in a subfolder where it wouldn't work. Depending on how the build/deploy is scripted, `netlify.toml` may not work. In this case we could revert to `_redirects`, but would have to place the `_redirects` …

Redirections Redux

---

docs/plugins/google-tagmanager/index.js

This is a hotfix, to include our [Klaro](https://kiprotect.com/docs/klaro/) consent management script in the docs deployments.

Hotfix: tracking consent in docs

---

docs/plugins/program_output.js

- Port [changes from `rasa`](https://github.com/RasaHQ/rasa/pull/7093) to `rasa-sdk`

make remarkProgramOutput() version-aware

---

changelog/329.feature.md
rasa_sdk/executor.py
rasa_sdk/forms.py
rasa_sdk/interfaces.py
rasa_sdk/knowledge_base/actions.py
rasa_sdk/knowledge_base/storage.py
rasa_sdk/utils.py
tests/test_actions.py
tests/test_forms.py
tests/test_interfaces.py
tests/test_utils.py

- fix https://github.com/RasaHQ/rasa/issues/7156
- users can now override a method `required_slots` to specify slots which should be filled by the form. The `FormValidationAction` will look for a method `extract_<slot_name>` to extract these slots.
- in case the users overrode `required_slots`, the `FormValidationAction` will automatically set the `requested_slot` to the next `required_slot` which is currently not filled. Users can override this behavior by customizing `request_next_slot`. By default `request_next_slot` also considers slots which were mapped in the domain (if there were any mapped ones). 
- introduce a utility function `utils.call_potential_coroutine` to get rid of our checks `if is coroutine ... else ...`
I will update the Rasa Open Source …

Custom and dynamic slots

---

changelog/329.feature.md
rasa_sdk/forms.py
tests/test_forms.py

- follow up of https://github.com/RasaHQ/rasa/pull/7233 and https://github.com/RasaHQ/rasa-sdk/pull/329
- `required_slots` receive the slots which were mapped in the domain as parameter to make it explicit for users that this is something which `required_slots` should return
- warn if a slot was mapped in the domain and has an additional custom mapping within the SDK.

slot extractions v2

---

changelog/344.bugfix.md
rasa_sdk/forms.py
tests/test_forms.py

- (https://github.com/RasaHQ/rasa-sdk/issues/344)  Fix slots_mapped_in_domain, by stripping `validate_` from the name to get the form name
- Fix loop by first making a list out of slots.items, because during the loop slots can change.

Slots mapped in domain

---

.dockerignore

- the README.md file is required to build a Docker image

Remove README.md from .dockerignore

---

.github/workflows/continous-integration.yml
rasa_sdk/endpoint.py

- fix pycodestyle linting for forks
- previously this error happened during `Checkout target branch to be able to diff`
```
Run git fetch origin "master"
From https://github.com/RasaHQ/rasa-sdk
* branch            master     -> FETCH_HEAD
* [new branch]      master     -> origin/master
fatal: couldn't find remote ref logging-file-for-action
Error: Process completed with exit code 1.
```
- you can see the previous CI run for a test

fix pycodestyle for forks

---

.github/workflows/continous-integration.yml
scripts/publish_gh_release_notes.py

- Fixes #360 
- @m-vdb I am not 100% sure this is the best way to skip the changelogs, I tried to harmonize the `continuous-integration.yml` with what we have in `rasa-x`. Do let me know if there's a better way to do this / if I'm missing something! 🙏  

Skip publishing changelog for alphas or RCs

---

rasa_sdk/forms.py

Remove an unnecessary call to the `requested_slots` function when computing the next requested slot which was called twice in the same function. 

remove unnecessary call to required_slots function

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/continous-integration.yml
.github/workflows/documentation.yml
.github/workflows/security-scans.yml
.github/workflows/spellcheck.yml
Makefile
README.md
docs/docs/knowledge-base-actions.mdx
docs/docusaurus.config.js
docs/plugins/program_output.js
scripts/push_docs_to_branch.sh
scripts/release.py

Relates to https://github.com/RasaHQ/rasa/issues/6028
- Rename occurrences of `master` in the repository
- Some occurrences of `master` deal with other repositories outside of our control, so we can't change them.
- There are some occurrences of `RasaHQ/rasa@master` that should be addressed after we make the change in the Rasa repository
- When this PR is ready for merging, we should:

Rename occurrences of "master" to "main"

---

CHANGELOG.mdx
docs/docs/knowledge-base-actions.mdx

- Rename references to Rasa Open Source default branch
- Needs to wait for https://github.com/RasaHQ/rasa/pull/7742 to be merged

rename links to Rasa default branch

---

.github/workflows/security-scans.yml
docs/package.json
docs/yarn.lock

- Add "resolutions" to `package.json` to pin vulnerable libraries.
- ⚠️ I've ran `yarn why ...` to find out which dependencies depend on these libraries, and check that `redoc`, `netlify-cli` and `plugin-ideal-image` continue to work on dev and production build.

add resolutions in docs/package.json to fix vulnerabilities

---

CHANGELOG.mdx
changelog/306.feature.md
poetry.lock
pyproject.toml
rasa_sdk/version.py

- update dependencies
- prepare 2.3.0 release
- pin `uvloop` to < 0.15.0 as 0.15.0 is not compatible with Python 3.6 (https://github.com/MagicStack/uvloop/releases/tag/v0.15.0)

Prepare release 2.3.0

---

.github/workflows/documentation.yml
Makefile
scripts/push_docs_to_branch.sh

- Fix regex pattern in doc release script to match all micros. Until now it matched all the micros not containing a "0" digit (`2.2.1`, `2.2.7`, `2.2.12`), missing micros like `2.2.10` or `2.2.20`

fix regex pattern to match all new micro versions

---

docs/package.json
docs/plugins/included_source.js
docs/scripts/update_versioned_sources.js
scripts/push_docs_to_branch.sh

- Same changes as in this PR: https://github.com/RasaHQ/rasa/pull/7961
- After merging this, we'll need to execute the script on the `documentation` branch for all previous 2.x versions

script to update path of sources loaded with remark-source to a versioned path

---

changelog/8223.bugfix.md
docs/docs/sdk-dispatcher.mdx
docs/static/spec/action-server.yml
rasa_sdk/executor.py
rasa_sdk/knowledge_base/actions.py
tests/test_executor.py

- `utter_message` explicitly takes in `response` and `template`

utter_message explicitly takes in response and template

---

CHANGELOG.mdx

Hope it's obvious from the change but the --auto-reload bullet point was incorrectly pointing at an issue within the rasa project when it was meant to be the PR with a matching number in the rasa-sdk project.
This just fixes that tiny (but confusing) little mistake 🙂
- ...

Tiny Changelog error - pointing at wrong project

---

.github/dependabot.yml

- Add `/docs` to dependabot, auto-assign to `@RasaHQ/scale-squad`

Add docs to dependabot

---

docs/package.json
docs/yarn.lock

This reverts commit 76848258a4147f6902b63fc19d32c574ad66fc34.
- revert commit as this broke the CI for `make test docs`

Revert "Bump @mdx-js/mdx from 1.6.18 to 1.6.22 in /docs"

---

docs/docs/knowledge-base-actions.mdx

"utter_greet" is incorrectly listed as an intent in the knowledge base action story.  Replacing with correct intent "query_knowledge_base"
- ...
- [n/a?] added some tests for the functionality
- [n/a] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

Fix mistake in knowledge base action story example

---

poetry.lock
pyproject.toml

- Update urllib3 to 1.26.5 to fix [CVE-2021-33503](https://bugzilla.redhat.com/show_bug.cgi?id=1968074)

Fix CVE-2021-33503

---

rasa_sdk/forms.py

-  Removes outdated warning for the extraction of custom slot mappings that should be defined in 3.0 domain format.
(closes issue in rasa repo: https://github.com/RasaHQ/rasa/issues/10116)

Remove warning for custom slot mappings

---

.github/change_filters.yml
.github/workflows/documentation.yml
Makefile
docs/package.json

Relates to https://github.com/RasaHQ/rasa/pull/10568
- 2 workflow changes:
- On pull requests, build the docs, upload a preview to Netlify and add a comment to the PR with a link to the preview (only run the workflow if there were docs changes to avoid spamming devs). It uses the PR number for the deploy alias, so that it's deterministic.
- On the `documentation` branch, build the docs and upload a production build to Netlify. Upon failure, send a message to Slack.
- Secrets have been updated in the Repository settings
- Comment the 2 workflow jobs introduced in this PR (not the whole workflow file). This needs to happen on the `main` branch, and should be automatically propagated to the `documentation` branch. If not, for some reason, do it manually.
- Go to …

Build docs preview and production builds in GitHub CI

---

.github/workflows/documentation.yml

Relates to https://github.com/RasaHQ/rasa-sdk/pull/628
Adds missing env vars at the top of the documentation workflow

fix missing env vars in workflow

---

poetry.lock
pyproject.toml

- addresses ongoing issue in rasa-sdk #592 
The test pipeline is set up to run tests against python 3.9. `rasa` doesn't support `3.9` yet, but I added it as a supported version here to get the pipeline to pass.

Use prompt toolkit ^2.0

---

.github/dependabot.yml

- Rename in dependabot config
- @joejuzl can you rename the RasaHQ/enable-squad GitHub handle to RasaHQ/atom-squad upon merge of this PR?

rename enable-squad -> atom-squad

---

poetry.lock
pyproject.toml
rasa_sdk/endpoint.py

- Update Sanic to v21.12
due to changes/deprecations, this necessitates:
- update sanic-cors to v2.0.0 because it v1 does not support sanic v21.12
- update sanic testing to v0.8.0 because v0.7 performs an action deprecated in v21.12
- provide a constant string value for the app Sanic instance because the "\_\_name\_\_" variable contains a character unsupported in v21.12

Update Sanic to v21.12

---

poetry.lock
pyproject.toml
rasa_sdk/endpoint.py

Reverts RasaHQ/rasa-sdk#689
This should be a micro release. The changes should go in [3.0.x](https://github.com/RasaHQ/rasa-sdk/tree/3.0.x) instead

Revert "Update Sanic to v21.12"

---

docs/docs/deploy-action-server.mdx
docs/docusaurus.config.js

- Addresses https://rasahq.atlassian.net/browse/RS-8
- Update the links pointing at `/docs/rasa-x` to `/docs/rasa-enterprise` in the docs
- Update wording from `Rasa X` to `Rasa Enterprise` (it was so small that I couldn't resist)

Update /docs/rasa-x links

---

docs/docs/knowledge-base-actions.mdx

- Fix "sobject_type" spelling error in knowledge-base-actions docs
- #789

Fix spelling error in knowledge-base-actions docs

---

changelog/836.improvement.md
docs/static/spec/action-server.yml
rasa_sdk/endpoint.py
tests/test_actions.py
tests/test_endpoint.py

- handle exceptions thrown in custom actions
- return a 500 response code as well as information about the error 
- compatible change since we already by default returned a 500 (sanic default). but exception was not properly logged to logger

created catch all for exceptions to handle them properly

---

CHANGELOG.mdx
changelog/_template.md.jinja2
scripts/publish_gh_release_notes.py

- fixed release note generation
- adds some whitespace to the changelog
- fixed the github release notes script to work even if no content is added for release (but still fail if the content can not be found at all)

fixed release note generation

---

.github/workflows/continuous-integration.yml
.github/workflows/documentation.yml
.github/workflows/security-scans.yml
.github/workflows/spellcheck.yml

Proposed changes:
- Pin CI runners to use Ubuntu 20.04 instead of an arbitrary "latest" build to avoid workflows breaking.

Fix GitHub runners to use ubuntu-20.04

---

changelog/912.improvement.md
rasa_sdk/endpoint.py
tests/test_endpoint.py

- Addresses https://rasahq.atlassian.net/browse/ENG-123
- gives action server the ability to decompress deflate encoded data

handling deflate encoded data in web hook

---

pyproject.toml
rasa_sdk/forms.py
tests/test_forms.py

Support validation actions for slots with `.` in name
To support spaces slots.

Add support of validation of slots with . in name

---

changelog/959.misc.md
poetry.lock
pyproject.toml

- Sanic `21.12.0` breaks with `websockets==11.0`, [add a constraint to fix it for the time being](https://github.com/sanic-org/sanic/issues/2733)

add constraint on websockets from sanic

---

changelog/1219.bugfix.md
rasa_sdk/plugin.py
tests/test_plugin.py

- Fixes the `logger.info` when plugins not found to `logger.debug`

fix: logger message to debug when plugins not found

---

.github/workflows/continuous-integration.yml
poetry.lock
pyproject.toml

[ATO-1282] Set setuptools version

---

.github/workflows/security-scans.yml

- Remove the explicit Snyk run from CI as this is now handled through the Github integration and it's duplicating results.

Remove Explicit Snyk step

---

changelog/1055.bugfix.md
poetry.lock

- Fixes [ATO-1938](https://rasahq.atlassian.net/browse/ATO-1938)
[ATO-1938]: https://rasahq.atlassian.net/browse/ATO-1938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Port Certifi vulnerability fix - 3.7.x

---

changelog/1072.improvement.md
rasa_sdk/cli/arguments.py
rasa_sdk/constants.py
tests/test_arguments.py

- Fixes [ATO-1661](https://rasahq.atlassian.net/browse/ATO-1661)
-
[ATO-1661]: https://rasahq.atlassian.net/browse/ATO-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-1661] Add `--endpoints` flag to rasa-sdk cli

---

changelog/1074.improvement.md
rasa_sdk/tracing/config.py
rasa_sdk/tracing/instrumentation/attribute_extractors.py
rasa_sdk/tracing/instrumentation/instrumentation.py
tests/test_endpoint.py
tests/tracing/instrumentation/conftest.py
tests/tracing/instrumentation/test_validation_action.py

- Fixes [ATO-2102](https://rasahq.atlassian.net/browse/ATO-2102)
View from Jaegar UI:
[ATO-2102]: https://rasahq.atlassian.net/browse/ATO-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-2102] Instrument `ValidationAction.run`

---

changelog/1076.improvement.md
rasa_sdk/tracing/instrumentation/attribute_extractors.py
rasa_sdk/tracing/instrumentation/instrumentation.py
tests/tracing/instrumentation/conftest.py
tests/tracing/instrumentation/test_action_executor.py

- Fixes [ATO-2131](https://rasahq.atlassian.net/browse/ATO-2131)
Views from Jaegar UI
[ATO-2131]: https://rasahq.atlassian.net/browse/ATO-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-2131] Instrument ActionExecutor._create_api_response

---

changelog/1077.improvement.md
rasa_sdk/tracing/config.py
rasa_sdk/tracing/instrumentation/attribute_extractors.py
rasa_sdk/tracing/instrumentation/instrumentation.py
tests/test_endpoint.py
tests/tracing/instrumentation/conftest.py
tests/tracing/instrumentation/test_form_validation_action.py
tests/tracing/instrumentation/test_validation_action.py

- Fixes [ATO-2103](https://rasahq.atlassian.net/browse/ATO-2103)
[ATO-2103]: https://rasahq.atlassian.net/browse/ATO-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-2103] Instrument FormValidationAction._extract_validation_events

---

changelog/1078.improvement.md
rasa_sdk/interfaces.py
rasa_sdk/types.py
tests/conftest.py
tests/test_actions.py
tests/test_endpoint.py
tests/test_interfaces.py
tests/tracing/test_utils.py

- Fixes [ATO-2188](https://rasahq.atlassian.net/browse/ATO-2188)
[ATO-2188]: https://rasahq.atlassian.net/browse/ATO-2188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-2188] Allow access to Dialogue stack from custom actions

---

.github/workflows/continuous-integration.yml

- Updated release success channel to #release and failure to #dev-tribe

Update slack release notifications channels

---

.github/workflows/security-patching.yml

- Remove the datestamped security patch image to enable us to tidy up older untagged images from Artifact Registry.

Remove Datestamped Security Patch Image

---

.github/workflows/rasa-sdk-dev-docker-image.yml

- Add new workflow to push docker images to AWS with latest tag once everyday.

Add new workflow to push docker dev images to AWS everyday

---

.github/workflows/continuous-integration.yml
Makefile

Add Makefile target to check if gRPC `.proto` files and generated Python code are in sync.
Target is part of existing `make lint` which is already part of CI.

[ATO-1652] Add target to check if gRPC code is in sync with generated python code

---

proto/action_webhook.proto
rasa_sdk/grpc_py/action_webhook_pb2.py
rasa_sdk/grpc_py/action_webhook_pb2.pyi
rasa_sdk/grpc_server.py
tests/conftest.py
tests/test_grpc_server.py

Add unit tests for GRPCActionServerWebhook

[ATO-1652] Add unit tests for GRPCActionServerWebhook

---

changelog/1113.misc.md
rasa_sdk/endpoint.py
rasa_sdk/interfaces.py

- Updated the log message from error to debug
- Rephrased the message so it's less alarming and actions are more clear
You can see here, when `--debug` is used, debug logs make a lot of sense. Request is received, domain context is missing, request is received again, running action is finished:

Change missing domain log level in rasa-sdk from ERROR to DEBUG

---

changelog/1117.bugfix.md
rasa_sdk/endpoint.py
rasa_sdk/grpc_server.py
rasa_sdk/tracing/utils.py
tests/tracing/test_utils.py

Add tracing between Rasa and action server.

[ATO-2609] Add gRPC tracing

---

changelog/1120.misc.md
rasa_sdk/endpoint.py

- Explicitly filter out Sanic warnings after Sanic is initialized

Explicitly filter out Sanic warnings after Sanic is initialized

---

.github/workflows/continuous-integration.yml
.github/workflows/rasa-sdk-dev-docker-image.yml
changelog/1123.misc.md

- Fixes [ATO-2602](https://rasahq.atlassian.net/browse/ATO-2602)
[ATO-2602]: https://rasahq.atlassian.net/browse/ATO-2602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for ARM arch for rasa-sdk Docker images

---

changelog/1122.improvement.md
rasa_sdk/__main__.py
rasa_sdk/cli/arguments.py

- Added --actions-module argument to explicitly specify the path where the custom actions are stored. Should be used on priority compared to `--actions` argument that will get deprecated.

Add —actions-module argument

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
README.md
changelog/1130.misc.md
poetry.lock
pyproject.toml
rasa_sdk/interfaces.py
rasa_sdk/knowledge_base/actions.py
rasa_sdk/knowledge_base/storage.py
rasa_sdk/knowledge_base/utils.py
rasa_sdk/tracing/endpoints.py
rasa_sdk/tracing/tracer_register.py
rasa_sdk/types.py
rasa_sdk/utils.py
tests/conftest.py
tests/knowledge_base/test_actions.py
tests/test_forms.py
tests/test_interfaces.py
tests/tracing/conftest.py
tests/tracing/instrumentation/conftest.py
tests/tracing/instrumentation/test_action_executor.py
tests/tracing/instrumentation/test_form_validation_action.py
tests/tracing/instrumentation/test_tracing.py
tests/tracing/instrumentation/test_validation_action.py
tests/tracing/test_utils.py

Update `ruff` to 0.3.7
Use `ruff` as code formatter.
Some files had to be reformatted.
A few lines of code needed to be updated to follow the linter rules.

Update to ruff 0.3.7 on 3.9.x

---

changelog/1135.misc.md
rasa_sdk/tracing/instrumentation/attribute_extractors.py
rasa_sdk/tracing/utils.py

- Fixes [ATO-2697](https://rasahq.atlassian.net/browse/ATO-2697)
[ATO-2697]: https://rasahq.atlassian.net/browse/ATO-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-2697] Stringify None attribute values to fix opentelemetry warning

---

.github/workflows/tag-release.yml
Makefile
README.md
scripts/release.py

Introduce mechanism to automatically create and push tag for release, similar to how it is already done in `rasa-private`. Summary of changes:
1. Updated `scripts/release.py` to create and push release tag, if invoked with `--tag` flag.
2. Updated `Makefile` with new target `make tag-release`.
3. Added GHA workflow `tag-release`, to do this in CI, when PR is merged to `main` or a release branch.
-    Manually tested this locally, as described below*
-    Not required I think as this is internal-only change, and not user facing?
*Ran `make release` and `make tag-release` locally, to see that a tag is created and pushed (**Note**: Tagging function checks that the branch is `main` or a final release branch (complying to …

ENG-1235: Push release tags automatically on `rasa-sdk`

---

.github/workflows/release-artifacts.yml
.github/workflows/tag-release.yml

Enable triggering release-tagging workflow manually on-demand also, in case previous auto-run(s) had failed, and we want to re-run on existing `prepared-release-` branch.
-   N/A
-   N/A
-   N/A
-   N/A

ENG-1235: Enable triggering release-tagging workflow manually on-demand also

---

.github/workflows/release.yml

[Jira task](https://rasahq.atlassian.net/browse/INFRA-1118)
- Detect if it's a minor release

[INFRA-1118] Add minor release detection

---

.github/workflows/release-artifacts.yml

remove small typo in release notifications

---

.github/workflows/release-artifacts.yml

[Jira task](https://rasahq.atlassian.net/browse/INFRA-1144)
- Segregate PyPi from Docker image job
- Update dependencies

[INFRA-1144] Segregate PyPi from Docker image job

---

.github/workflows/continuous-integration.yml
.github/workflows/dev-release.yml
.github/workflows/git-backup.yml
.github/workflows/pr-cleanup.yml
.github/workflows/pr-merged.yml
.github/workflows/release-artifacts.yml
.github/workflows/release.yml
.github/workflows/scan_docker_image_dependencies.yml
.github/workflows/security-patching.yml
.github/workflows/security-scans.yml
.github/workflows/semgrep-check.yml
.github/workflows/spellcheck.yml

[JIRA](https://rasahq.atlassian.net/browse/INFRA-1111)

[INFRA-1111] Bump github actions runner OS version to ubuntu-24.04

---

.github/workflows/release-artifacts.yml

[JIRA](https://rasahq.atlassian.net/browse/INFRA-1152)
- Create a job `define-release-version` where the release version will be defined and made available to parent jobs.

[INFRA-1152] Fix publish release notes step

---

.github/workflows/dev-release.yml
.github/workflows/release-artifacts.yml

[JIRA](https://rasahq.atlassian.net/browse/INFRA-1152)

[INFRA-1152] Fix release workflows

---

rasa_sdk/executor.py

- Do not use relpath because it doesnt work well on windows; it caused a failure in Rasa Pro CI windows tests, see [this PR](https://github.com/RasaHQ/rasa-private/pull/1778)

Do not use relpath because it doesnt work well on windows

---

.github/actions/setup-python-env/action.yml
.github/workflows/continuous-integration.yml
.github/workflows/release.yml

Update `actions/cache` to `actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57` (version 4.2.0).

Update actions/cache to 4.2.0

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-cleanup.yml

- Rasa Pro CI cluster will be in eu-west-1, so wee need to keep the images in the same zone to avoid additional fees
- Change AWS region for DEV docker images to eu-west-1

Change AWS region for DEV docker images to eu

---

.github/workflows/release-artifacts.yml

- Move notifications from `#dev-tribe` to `#prodeng-internal`

Update slack notification channel to #prodeng-internal
